/*

 HOT DOG Linux

 Copyright (c) 2020 Arthur Choung. All rights reserved.

 Email: arthur -at- hotdoglinux.com

 This file is part of HOT DOG Linux.

 HOT DOG Linux is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>.

 */

/* NOTE: This file was generated by parse-functions.pl */

@interface NSObject(rUFDZqfSNkEFjLmYusBDyUijgrDziBP)
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)outerRect;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)flashIndex:(int)index duration:(int)duration;
- (id)init;
- (void)updateMenuBar;
- (void)dealloc;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (id)dictForX:(int)x;
- (void)handleRightMouseDown:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)openRootMenu:(id)dict x:(int)mouseRootX;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (void)testAddAmigaWindow;
+ (void)enterAmigaMode;
+ (char *)cStringForAmigaPalette;
+ (char *)cStringForAmigaHighlightedPalette;
+ (char *)cStringForAmigaTitleBarTextBackground;
+ (char *)cStringForAmigaTitleBarCloseButton;
+ (char *)cStringForAmigaTitleBarLowerButton;
+ (char *)cStringForAmigaTitleBarRaiseButton;
+ (char *)cStringForAmigaTitleBarLeft;
+ (char *)cStringForAmigaTitleBarMiddle;
+ (char *)cStringForInactiveAmigaTitleBar;
+ (char *)cStringForAmigaTitleBarRight;
+ (char *)cStringForAmigaHorizontalScrollBarLeft;
+ (char *)cStringForAmigaHorizontalScrollBarMiddle;
+ (char *)cStringForAmigaHorizontalScrollBarRight;
+ (char *)cStringForAmigaFuelGaugeTop;
+ (char *)cStringForAmigaFuelGaugeMiddle;
+ (char *)cStringForAmigaFuelGaugeBottom;
+ (void)drawAmigaHorizontalScrollBarInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawAmigaFuelGaugeInBitmap:(id)bitmap rect:(Int4)r;
+ (char *)cStringForAmigaVerticalScrollBarTop;
+ (char *)cStringForAmigaVerticalScrollBarMiddle;
+ (char *)cStringForAmigaVerticalScrollBarBottom;
+ (void)drawAmigaVerticalScrollBarInBitmap:(id)bitmap rect:(Int4)r;
+ (char *)cStringForAmigaResizeButton;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)flashIndex:(int)index duration:(int)duration;
- (id)init;
- (void)updateMenuBar;
- (void)dealloc;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (id)dictForX:(int)x;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)openRootMenu:(id)dict x:(int)mouseRootX;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (void)enterAtariSTMode;
+ (char *)cStringForAtariSTInactiveTitleBarLeft;
+ (char *)cStringForAtariSTInactiveTitleBarMiddle;
+ (char *)cStringForAtariSTInactiveTitleBarRight;
+ (char *)cStringForAtariSTInactiveBottomBorderLeft;
+ (char *)cStringForAtariSTInactiveBottomBorderMiddle;
+ (char *)cStringForAtariSTInactiveBottomBorderRight;
+ (char *)cStringForAtariSTActiveTitleBarLeft;
+ (char *)cStringForAtariSTActiveTitleBarMiddle;
+ (char *)cStringForAtariSTActiveTitleBarRight;
+ (char *)cStringForAtariSTLeftBorderMiddle;
+ (char *)cStringForAtariSTBottomBorderLeft;
+ (char *)cStringForAtariSTBottomBorderMiddle;
+ (char *)cStringForAtariSTBottomBorderRight;
+ (char *)cStringForAtariSTRightBorderTop;
+ (char *)cStringForAtariSTRightBorderMiddle;
+ (char *)cStringForAtariSTRightBorderBottom;
+ (char *)cStringForAtariSTInactiveRightBorderMiddle;
+ (char *)cStringForAtariSTCloseButton;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (id)init;
- (void)updateBackgroundAgents;
- (void)dealloc;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (id)HotDog;
+ (id)BananaPeel;
+ (id)BitmapMenuItem:(id)name;
- (int)preferredWidth;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawHighlightedInBitmap:(id)bitmap rect:(Int4)r;
- (id)init;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (void)setup;
- (void)setupBall;
- (void)setupBricks;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesMoved:(id)event;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)autoMove;
- (void)updateBitmap;
- (id)init;
- (BOOL)glNearest;
- (int)preferredWidth;
- (int)preferredHeight;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (id)stripTrailingZeroes:(id)str;
- (id)performCalculation;
- (Int4)rectForButton:(char)c;
- (char)buttonForEvent:(id)event;
- (char)buttonForTouch:(id)event;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesMoved:(id)event;
- (void)handleTouchesEnded:(id)event;
- (void)handleTouchesCancelled:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleButton:(char)button;
- (void)updateBitmap;
- (void)dealloc;
- (id)init;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (void)setup;
- (void)setupMushrooms;
- (int)indexOfPartialMushroom;
- (int)numberOfMushrooms;
- (void)setupCentipede;
- (int)numberOfCentipede;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesEnded:(id)event;
- (void)handleTouchesCancelled:(id)event;
- (void)handleTouchesMoved:(id)event;
- (void)moveCentipede;
- (void)checkCentipedeCollision;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)updateState;
- (void)updateBitmap;
+ (id)testCheckbox:(id)text path:(id)path;
+ (char *)cStringForCheckbox;
+ (char *)cStringForCheckboxSelected;
+ (char *)cStringForCheckboxDown;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)setChecked:(BOOL)val;
+ (id)CommandOutputBitmap:(id)cmd;
- (int)fileDescriptor;
- (void)handleData:(id)data;
- (void)handleFileDescriptor;
- (int)preferredWidth;
- (int)preferredHeight;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)drawHighlightedInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (id)CommandOutputText:(id)cmd;
+ (id)CommandOutputText:(id)cmd lineMessage:(id)lineMessage;
- (int)fileDescriptor;
- (void)handleFileDescriptor;
- (int)preferredWidth;
- (int)preferredWidthForBitmap:(id)bitmap;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawHighlightedInBitmap:(id)bitmap rect:(Int4)r;
#ifdef BUILD_FOR_LINUX
+ (BOOL)confirmWithAlert:(id)text;
+ (BOOL)confirmWithAlert:(id)text title:(id)title;
- (void)choosePathWithActionSheet:(id)choices continuation:(id)continuation;
- (void)confirmWithAlert:(id)text title:(id)title continuation:(id)continuation;
- (void)confirmWithAlert:(id)text title:(id)title okText:(id)okText continuation:(id)continuation;
#endif
+ (id)ConfirmationDialog:(id)text okText:(id)okText;
+ (id)ConfirmationDialog:(id)text;
+ (int)preferredHeightForConfirmationDialog:(id)text width:(int)width;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (char *)cStringForBitmapErrorIcon;
+ (int)preferredHeightForBitmapErrorAlert:(id)text width:(int)width;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (id)asBitmapErrorAlert;
+ (void)toggleExposeMode;
+ (void)enterExposeMode;
+ (void)exitExposeMode;
- (void)unmapIrrelevantWindows;
- (void)mapIrrelevantWindows;
- (void)tileWindows;
- (void)tileWindows:(id)windows monitor:(id)monitor;
- (void)revertWindowPositions;
- (void)handleDidSetInputFocusEvent:(id)event;
- (void)handleEnterWindowEvent:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
+ (id)classMenu;
- (BOOL)glNearest;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (void)updateBitmap;
- (int)indexForEmptySpace;
- (void)movePieces:(int)i :(int *)buf;
- (void)handleMouseDown:(id)event;
- (BOOL)isWinner;
- (BOOL)fY;
- (BOOL)fN;
- (void)fI;
- (void)fG;
- (void)fE;
- (void)fL;
- (void)solve;
- (void)setupTransition;
- (void)automaticallyMovePiece;
- (void)movePiece:(id)move;
- (void)scramble;
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
+ (char *)cStringForHotDogStandMenuBarButtons;
- (void)flashIndex:(int)index duration:(int)duration;
- (id)init;
- (void)updateMenuBar;
- (void)dealloc;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (id)dictForX:(int)x;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)openRootMenu:(id)dict x:(int)mouseRootX;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (void)enterHotDogStandMode;
+ (char *)cStringForHotDogStandHasFocusPalette;
+ (char *)cStringForHotDogStandActiveTitleBarLeft;
+ (char *)cStringForHotDogStandActiveTitleBarMiddle;
+ (char *)cStringForHotDogStandActiveTitleBarRight;
+ (char *)cStringForHotDogStandLeftBorderMiddle;
+ (char *)cStringForHotDogStandLeftBorderBottom;
+ (char *)cStringForHotDogStandBottomBorderLeft;
+ (char *)cStringForHotDogStandBottomBorderMiddle;
+ (char *)cStringForHotDogStandBottomBorderRight;
+ (char *)cStringForHotDogStandRightBorderMiddle;
+ (char *)cStringForHotDogStandRightBorderBottom;
+ (char *)cStringForHotDogStandMinimizeButtonDown;
+ (char *)cStringForHotDogStandMaximizeButtonDown;
+ (char *)cStringForHotDogStandCloseButtonDown;
+ (char *)cStringForHotDogStandSmallCloseButton;
+ (char *)cStringForHotDogStandSmallCloseButtonDown;
+ (char *)cStringForHotDogStandRevertButton;
+ (char *)cStringForHotDogStandRevertButtonDown;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (char)borderForX:(int)x y:(int)y w:(int)w h:(int)h;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (id)init;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)updateState;
- (void)updateBitmap;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesMoved:(id)event;
- (void)handleScrollWheel:(id)event;
+ (void)drawStripedBackgroundInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawTopListButtonInBitmap:(id)bitmap rect:(Int4)r palette:(char *)palette;
+ (void)drawMiddleListButtonInBitmap:(id)bitmap rect:(Int4)r palette:(char *)palette;
+ (void)drawBottomListButtonInBitmap:(id)bitmap rect:(Int4)r palette:(char *)palette;
+ (char *)cStringForBitmapBottomListButtonLeft;
+ (char *)cStringForBitmapBottomListButtonMiddle;
+ (char *)cStringForBitmapBottomListButtonRight;
+ (char *)cStringForBitmapMiddleListButtonLeft;
+ (char *)cStringForBitmapMiddleListButtonMiddle;
+ (char *)cStringForBitmapMiddleListButtonRight;
+ (char *)cStringForBitmapTopListButtonLeft;
+ (char *)cStringForBitmapTopListButtonMiddle;
+ (char *)cStringForBitmapTopListButtonRight;
- (id)menuFromPath;
#ifdef BUILD_FOR_IOS
- (id)arrayFromPath;
#endif
- (void)setAllMessageForClick:(id)val;
- (void)setAllStringFormat:(id)val;
#ifdef BUILD_FOR_IOS
- (id)asListInterface;
#else
- (id)asListInterface;
#endif
- (id)asListInterface;
#ifdef BUILD_FOR_IOS
- (id)asListInterfaceForPath;
- (id)asListInterfaceWithSortMessage:(id)message;
- (id)asListInterface;
#endif
+ (id)ListInterfaceWithMessage:(id)message observer:(id)observer;
- (id)init;
- (void)setup:(id)arr;
- (void)setupDict:(id)dict;
- (void)setupMessage:(id)message observer:(id)observer;
- (void)updateSearchText:(id)text;
- (void)updateFromCurrentDirectory;
- (void)updateArray;
- (int)fileDescriptor;
- (void)handleFileDescriptor;
- (void)beginIteration:(id)event rect:(Int4)r;
#if 0
- (id)handleUpdate;
#endif
- (void)updateObjectOffsetY:(int)delta;
- (void)handlePageUp;
- (void)handlePageDown;
- (void)handleMoveUp;
- (void)handleMoveDown;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesEnded:(id)event;
- (void)handleTouchesMoved:(id)event;
- (void)handleTouchesCancelled:(id)event;
- (id)buttonForMousePosEvent:(id)event;
- (void)handleScrollTouch:(id)event;
- (void)handleScrollWheel:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleRightMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawArray:(id)arr inBitmap:(id)bitmap rect:(Int4)rect;
- (void)drawElement:(id)elt inBitmap:(id)bitmap rect:(Int4)r style:(id)style type:(int)type;
#ifdef BUILD_FOR_OSX
#endif
+ (void)enterMacClassicMode;
+ (char *)cStringForMacClassicInactiveTitleBarLeft;
+ (char *)cStringForMacClassicInactiveTitleBarMiddle;
+ (char *)cStringForMacClassicInactiveTitleBarRight;
+ (char *)cStringForMacClassicInactiveBottomBorderLeft;
+ (char *)cStringForMacClassicInactiveBottomBorderMiddle;
+ (char *)cStringForMacClassicInactiveBottomBorderRight;
+ (char *)cStringForMacClassicActiveTitleBarLeft;
+ (char *)cStringForMacClassicActiveTitleBarMiddle;
+ (char *)cStringForMacClassicActiveTitleBarRight;
+ (char *)cStringForMacClassicLeftBorderMiddle;
+ (char *)cStringForMacClassicBottomBorderLeft;
+ (char *)cStringForMacClassicBottomBorderMiddle;
+ (char *)cStringForMacClassicBottomBorderRight;
+ (char *)cStringForMacClassicRightBorderTop;
+ (char *)cStringForMacClassicRightBorderMiddle;
+ (char *)cStringForMacClassicRightBorderBottom;
+ (char *)cStringForMacClassicInactiveRightBorderMiddle;
+ (char *)cStringForMacClassicCloseButtonDown;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (void)testAddMacColorWindow;
+ (void)drawActiveTitleBarInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawInactiveTitleBarInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawActiveScrollBarInBitmap:(id)bitmap rect:(Int4)r pct:(double)pct;
+ (void)drawInactiveHorizontalScrollBarInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawInactiveVerticalScrollBarInBitmap:(id)bitmap rect:(Int4)r;
+ (void)drawResizeButtonInBitmap:(id)bitmap x:(int)x y:(int)y;
+ (char *)cStringForTitleBarPalette;
+ (char *)cStringForTitleBarButtonDown;
+ (char *)cStringForTitleBarCloseButton;
+ (char *)cStringForTitleBarMaximizeButton;
+ (char *)cStringForInactiveTitleBarLeft;
+ (char *)cStringForActiveTitleBarLeft;
+ (char *)cStringForInactiveTitleBarMiddle;
+ (char *)cStringForActiveTitleBarMiddle;
+ (char *)cStringForInactiveTitleBarRight;
+ (char *)cStringForActiveTitleBarRight;
+ (char *)cStringForInactiveVerticalScrollBarPalette;
+ (char *)cStringForInactiveVerticalScrollBarUpArrow;
+ (char *)cStringForInactiveVerticalScrollBarMiddle;
+ (char *)cStringForInactiveVerticalScrollBarDownArrow;
+ (char *)cStringForActiveScrollBarPalette;
+ (char *)cStringForResizeButton;
+ (char *)cStringForActiveScrollBarLeftArrow;
+ (char *)cStringForActiveScrollBarMiddle;
+ (char *)cStringForActiveScrollBarRightArrow;
+ (char *)cStringForActiveScrollBarKnob;
+ (char *)cStringForInactiveHorizontalScrollBarPalette;
+ (char *)cStringForInactiveHorizontalScrollBarLeftArrow;
+ (char *)cStringForInactiveHorizontalScrollBarMiddle;
+ (char *)cStringForInactiveHorizontalScrollBarRightArrow;
+ (char *)cStringForScrollBarLeftArrowBlackAndWhite;
+ (char *)cStringForScrollBarRightArrowBlackAndWhite;
+ (char *)cStringForScrollBarMiddleBlackAndWhite;
+ (char *)cStringForScrollBarKnobBlackAndWhite;
+ (char *)cStringForResize;
+ (char *)cStringForMacWindowSelectionHorizontal;
+ (char *)cStringForMacWindowSelectionVertical;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (char *)cStringForUpperLeftMenuBar;
+ (char *)cStringForUpperRightMenuBar;
- (void)flashIndex:(int)index duration:(int)duration;
- (id)init;
- (void)updateMenuBar;
- (void)dealloc;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (id)dictForX:(int)x;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)openRootMenu:(id)dict x:(int)mouseRootX;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (char *)cStringForMacPlatinumBackgroundPalette;
+ (char *)cStringForMacPlatinumBackground;
+ (void)enterMacPlatinumMode;
+ (char *)cStringForMacPlatinumMenuBarPalette;
+ (char *)cStringForMacPlatinumMenuBarLeft;
+ (char *)cStringForMacPlatinumMenuBarMiddle;
+ (char *)cStringForMacPlatinumMenuBarRightPalette;
+ (char *)cStringForMacPlatinumMenuBarRight;
- (void)flashIndex:(int)index duration:(int)duration;
- (id)init;
- (void)updateMenuBar;
- (void)dealloc;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (id)fileDescriptorObjects;
- (id)dictForX:(int)x;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)openRootMenu:(id)dict x:(int)mouseRootX;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (char *)cStringForMacPlatinumInactiveTitleBarPalette;
+ (char *)cStringForMacPlatinumInactiveTitleBarLeft;
+ (char *)cStringForMacPlatinumInactiveTitleBarMiddle;
+ (char *)cStringForMacPlatinumInactiveTitleBarRight;
+ (char *)cStringForMacPlatinumInactiveLeftBorderPalette;
+ (char *)cStringForMacPlatinumInactiveBottomBorderPalette;
+ (char *)cStringForMacPlatinumInactiveBottomBorderLeft;
+ (char *)cStringForMacPlatinumInactiveBottomBorderMiddle;
+ (char *)cStringForMacPlatinumInactiveBottomBorderRight;
+ (char *)cStringForMacPlatinumActiveTitleBarLeftPalette;
+ (char *)cStringForMacPlatinumActiveTitleBarLeft;
+ (char *)cStringForMacPlatinumActiveTitleBarRightPalette;
+ (char *)cStringForMacPlatinumActiveTitleBarMiddle;
+ (char *)cStringForMacPlatinumActiveTitleBarRight;
+ (char *)cStringForMacPlatinumActiveTitleBarTextLeft;
+ (char *)cStringForMacPlatinumActiveTitleBarTextRight;
+ (char *)cStringForMacPlatinumLeftBorderPalette;
+ (char *)cStringForMacPlatinumLeftBorderMiddle;
+ (char *)cStringForMacPlatinumBottomBorderPalette;
+ (char *)cStringForMacPlatinumBottomBorderLeft;
+ (char *)cStringForMacPlatinumBottomBorderMiddle;
+ (char *)cStringForMacPlatinumBottomBorderRight;
+ (char *)cStringForMacPlatinumRightBorderPalette;
+ (char *)cStringForMacPlatinumRightBorderTop;
+ (char *)cStringForMacPlatinumRightBorderMiddle;
+ (char *)cStringForMacPlatinumRightBorderBottom;
+ (char *)cStringForMacPlatinumInactiveRightBorderPalette;
+ (char *)cStringForMacPlatinumInactiveRightBorderTop;
+ (char *)cStringForMacPlatinumInactiveRightBorderMiddle;
+ (char *)cStringForMacPlatinumCloseButtonDownPalette;
+ (char *)cStringForMacPlatinumCloseButtonDown;
+ (char *)cStringForMacPlatinumShadeButtonDownPalette;
+ (char *)cStringForMacPlatinumShadeButtonDown;
+ (char *)cStringForMacPlatinumMaximizeButtonDownPalette;
+ (char *)cStringForMacPlatinumMaximizeButtonDown;
+ (char *)cStringForMacPlatinumMoveSelectionTopLeft;
+ (char *)cStringForMacPlatinumMoveSelectionTop;
+ (char *)cStringForMacPlatinumMoveSelectionLeft;
+ (char *)cStringForMacPlatinumMoveSelectionRight;
+ (char *)cStringForMacPlatinumMoveSelectionBottom;
+ (char *)cStringForMacPlatinumResizeSelectionHorizontal;
+ (char *)cStringForMacPlatinumResizeSelectionVertical;
- (id)init;
- (void)calculateRects:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r context:(id)context;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (void)enterMacColorMode;
- (BOOL)shouldPassthroughClickToFocus;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleRightMouseDown:(id)event;
- (id)asMenu;
- (void)dealloc;
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)outerRect;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)showAlert;
#ifdef BUILD_FOR_LINUX
+ (void)showAlert:(id)text;
- (void)showAlert;
#endif
+ (char *)cStringForBitmapMessageIcon;
+ (int)preferredHeightForBitmapMessageAlert:(id)text width:(int)width;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleCloseEvent:(id)event;
- (id)asBitmapMessageAlert;
+ (id)ObjectInterface;
#ifdef BUILD_FOR_IOS
+ (id)ListInterface;
#else
+ (id)ListInterface;
#endif
- (void)generateClassMenuNamesIfNecessary;
- (void)handleClassMenuKeyDown:(id)str;
- (void)handleClassMenuForKey:(id)key value:(id)value;
+ (id)classMenuForObject;
- (id)classMenuForObject;
+ (void)drawForwardButtonInBitmap:(id)bitmap rect:(Int4)r palette:(char *)palette;
+ (void)drawBackButtonInBitmap:(id)bitmap rect:(Int4)r palette:(char *)palette;
+ (void)fixupEvent:(id)event forBitmapObject:(id)obj;
+ (char *)cStringForBitmapBackButtonLeft;
+ (char *)cStringForBitmapBackButtonMiddle;
+ (char *)cStringForBitmapBackButtonRight;
+ (char *)cStringForBitmapForwardButtonLeft;
+ (char *)cStringForBitmapForwardButtonMiddle;
+ (char *)cStringForBitmapForwardButtonRight;
- (id)asNavigationInterface;
+ (void)popFromMainInterface;
+ (int)navigationBarHeight;
#ifdef BUILD_FOR_OSX
+ (id)mainInterface;
#endif
#ifdef BUILD_FOR_IOS
+ (id)mainInterface;
#endif
#ifdef BUILD_FOR_LINUX
+ (id)mainInterface;
#endif
#ifdef BUILD_FOR_IOS
+ (id)interfaceObject;
+ (id)interfaceValueForKey:(id)key;
#else
+ (id)interfaceObject;
+ (id)interfaceValueForKey:(id)key;
#endif
#ifdef BUILD_FOR_IOS
- (void)pushToMainInterface;
#else
- (void)pushToMainInterface;
- (void)pushToMainInterface;
- (void)pushToMainInterface;
- (void)pushToMainInterface;
#endif
- (void)drawTransitionInBitmap:(id)bitmap rect:(Int4)r;
- (void)transition:(id)transition context:(id)nextContext;
- (void)popToObject:(id)obj;
- (void)popObject;
- (void)pushObject:(id)obj;
- (int)fileDescriptor;
- (void)handleFileDescriptor;
- (id)fileDescriptorObjects;
- (void)handleBackgroundUpdate:(id)event;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
#ifdef BUILD_FOR_OSX
#endif
- (void)endIteration:(id)event;
- (id)buttonForMousePosEvent:(id)event;
- (void)handleMagnify:(id)event;
- (void)handleScrollWheel:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleRightMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleRightMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleKeyDown:(id)event;
- (void)handleKeyUp:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
#ifdef BUILD_FOR_LINUX
#ifdef BUILD_FOR_ANDROID
#else
#endif
#endif
- (void)drawNavigationBarInBitmap:(id)bitmap rect:(Int4)rect title:(id)title backButton:(id)backButton forwardButton:(id)forwardButton;
- (void)goBack;
+ (id)testRadioButtons:(id)filePath;
+ (char *)cStringForRadioButtonSelected;
+ (char *)cStringForRadioButton;
+ (char *)cStringForRadioButtonDown;
- (id)init;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)updateSelectedIndex;
- (int)preferredWidth;
- (int)preferredHeight;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
+ (id)writeAllCardsToFiles;
#ifdef BUILD_FOR_IOS
#else
+ (BOOL)isiPad;
#endif
+ (id)generateAppCardIconBitmap;
+ (id)generateiPadProCardIconBitmap;
+ (id)generateiPadCardIconBitmap;
+ (id)generateiPhoneCardIconBitmap;
+ (id)generateCardIconImage;
+ (id)deckOfCards:(int)numberOfCards;
+ (id)shuffledDeckOfCards:(int)numberOfCards;
+ (id)textForCard:(int)index;
+ (id)classMenu;
#ifdef BUILD_FOR_IOS
#endif
- (id)textForCardsOnTopOfCards;
- (void)fixmeMoveComplete;
- (void)fixmeMoveDeck;
- (id)init;
- (int)topmostCardForPile:(int)pile;
- (id)probabilitiesForValidFacedownCard;
- (id)ranksOfTopmostCards;
- (id)textForTopmostCards;
- (id)ranksOfFacedownCards;
- (id)textForFacedownCards;
- (id)textForFaceupCards;
- (id)tabBarImage;
- (BOOL)isAnimating;
- (BOOL)shouldAnimate;
- (void)beginIteration:(id)event rect:(Int4)r;
- (void)updateState;
- (int)bitmapWidth;
- (int)bitmapHeight;
- (unsigned char *)pixelBytesRGBA8888;
- (void)updateBitmap;
- (void)setup;
- (void)dealCards;
- (int)cardForX:(int)x y:(int)y underneathCard:(int)card;
- (int)cardAtX:(int)x y:(int)y;
- (int)cardForX:(int)x y:(int)y;
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleTouchesBegan:(id)event;
- (void)handleTouchesEnded:(id)event;
- (void)handleTouchesMoved:(id)event;
- (void)handleTouchesCancelled:(id)event;
- (void)moveTopCardToX:(int)x y:(int)y;
- (void)moveCard:(int)card x:(int)x y:(int)y;
- (void)movePileOfCards:(int)bottomOfPile x:(int)x y:(int)y;
- (void)raiseCard:(int)index;
- (int)fixupPile:(int)card;
- (BOOL)isMovablePile:(int)bottomOfPile;
- (int)cardUnderneathRect:(Int4)cardRect;
- (int)validCardUnderneathCard:(int)card;
- (int)cardUnderneathCard:(int)card;
- (int)bottommostCardUnderneathCard:(int)card;
- (int)cardOnTopOfCard:(int)card;
- (int)topmostCardOnTopOfCard:(int)card;
- (BOOL)isCompleteSuitOfCards:(int)card;
- (void)moveCompleteSuitOfCards:(int)card;
#ifdef BUILD_FOR_LINUX
#else
#endif
- (int)preferredWidth;
- (int)preferredHeight;
- (BOOL)shouldAnimate;
#ifdef BUILD_FOR_LINUX
#else
#endif
- (void)calculateRects:(Int4)r;
- (void)beginIteration:(id)event rect:(Int4)r;
#ifdef BUILD_FOR_LINUX
- (double)timeDifference:(struct timespec)time1 :(struct timespec)time2;
#else
- (double)timeDifference:(double)time1 :(double)time2;
#endif
- (id)timeDifferenceAsString:(double)diff_time;
- (void)handleStartButton;
#ifdef BUILD_FOR_LINUX
#else
#endif
- (void)handleResetButton;
#ifdef BUILD_FOR_LINUX
#else
#endif
- (void)handleMouseDown:(id)event;
- (void)handleMouseUp:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
#ifdef BUILD_FOR_LINUX
#else
#endif
#ifdef BUILD_FOR_LINUX
#else
#endif
#ifdef BUILD_FOR_LINUX
#else
#endif
+ (id)testTextField;
- (void)handleBackgroundUpdate:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleKeyDown:(id)event;
- (void)handleKeyUp:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleOKButton:(id)event;
- (void)handleCancelButton:(id)event;
- (id)valuesForAllIvars;
+ (id)selectorMenu;
+ (id)testTextFields;
- (id)asTextFieldsForSelector;
- (void)handleBackgroundUpdate:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleKeyDown:(id)event;
- (void)handleKeyUp:(id)event;
#ifdef BUILD_FOR_LINUX
+ (id)inputNumberWithAlert:(id)text;
+ (id)inputTextWithAlert:(id)text;
- (void)inputNumberWithAlert:(id)text title:(id)title key:(id)key continuation:(id)continuation;
- (void)inputTextWithAlert:(id)text title:(id)title key:(id)key continuation:(id)continuation;
#endif
+ (id)TextInputDialog:(id)text field:(id)field;
+ (int)preferredHeightForTextInputDialog:(id)text width:(int)width;
- (void)handleBackgroundUpdate:(id)event;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)handleKeyDown:(id)event;
- (void)handleKeyUp:(id)event;
- (void)handleMouseDown:(id)event;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)handleOKButton:(id)event;
- (void)handleCancelButton:(id)event;
+ (id)TextMenuItem:(id)text;
- (int)preferredWidth;
- (int)preferredWidthForBitmap:(id)bitmap;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawHighlightedInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
+ (char *)cStringForBitmapVerticalSliderTop;
+ (char *)cStringForBitmapVerticalSliderMiddle;
+ (char *)cStringForBitmapVerticalSliderBottom;
+ (char *)cStringForBitmapVerticalSliderKnob;
+ (void)drawVerticalSliderInBitmap:(id)bitmap rect:(Int4)r pct:(double)pct;
- (id)init;
- (int)preferredWidth;
- (int)preferredHeight;
- (int)fileDescriptor;
- (void)handleFileDescriptor;
- (void)handleMouseMoved:(id)event;
- (void)handleMouseUp:(id)event;
- (void)updateVolumeSlider;
- (void)drawInBitmap:(id)bitmap rect:(Int4)r;
- (void)drawVolumeSliderInBitmap:(id)bitmap rect:(Int4)r pct:(double)pct;
- (id)currentDateTimeForTimeZoneWithFormat:(id)format;
- (id)asArrayWithLeftStringFormat:(id)leftStringFormat rightStringFormat:(id)rightStringFormat messageForClick:(id)messageForClick;
- (id)asArrayWithStringFormat:(id)stringFormat messageForClick:(id)messageForClick;
+ (id)timezoneTable;
- (id)parseTimezoneTableFile;
+ (id)testWorldClock;
@end
