#!/usr/bin/python

import subprocess
import json

def asQuotedString(str):
    if str == None:
        return ""
    str = str.replace('\\', '\\\\');
    str = str.replace('"', '\\"');
    return "\"%s\"" % (str)

def dhcpcdIsRunning(name):
    try:
        output = subprocess.check_output(['pgrep', '-fx', 'dhcpcd ' + name])
        return 1
    except subprocess.CalledProcessError as e:
        pass
    return 0

output = subprocess.check_output(['ip', '-j', '-p', 'link', 'show'])
obj = json.loads(output)
keys = ['ifname', 'link_type', 'up', 'lowerUp', 'operstate', 'address', 'dhcpcdIsRunning']
print(",".join(keys))
for elt in obj:
    if "UP" in elt['flags']:
        elt['up'] = "1"
    else:
        elt['up'] = "0"
    if "LOWER_UP" in elt['flags']:
        elt['lowerUp'] = "1"
    else:
        elt['lowerUp'] = "0"
    elt['dhcpcdIsRunning'] = "0"
    if 'ifname' in elt:
        if dhcpcdIsRunning(elt['ifname']):
            elt['dhcpcdIsRunning'] = "1"
    tokens = map(lambda x: asQuotedString(elt[x]), keys)
    print(",".join(tokens))

