#!/usr/bin/perl

use JSON;

sub asQuotedString
{
    my ($str) = @_;
    $str =~ s/\\/\\\\/g;
    $str =~ s/\"/\\\"/g;
    return '"' . $str . '"';
}

sub dhcpcdIsRunning
{
    my ($arg) = @_;
    return `pgrep -fx 'dhcpcd $arg'`;
}

$output = `ip -j -p link show`;
$result = decode_json($output);
$keys = 'ifname,link_type,up,lowerUp,operstate,address,dhcpcdIsRunning';
print "$keys\n";
foreach $elt (@$result) {
    if (grep /^UP$/, @{$elt->{'flags'}}) {
        $elt->{'up'} = '1';
    } else {
        $elt->{'up'} = '0';
    }
    if (grep /^LOWER_UP$/, @{$elt->{'flags'}}) {
        $elt->{'lowerUp'} = '1';
    } else {
        $elt->{'lowerUp'} = '0';
    }
    $elt->{'dhcpcdIsRunning'} = '0';
    if ($elt->{'ifname'}) {
        if (dhcpcdIsRunning($elt->{'ifname'})) {
            $elt->{'dhcpcdIsRunning'} = '1';
        }
    }
    @tokens = map { asQuotedString($elt->{$_}) } split ',', $keys;
    print join ',', @tokens;
    print "\n";
}

