#!/usr/bin/perl

$|=1;

for(;;) {

    $output = `ifconfig`;
    @lines = split '\n', $output;

    foreach $line (@lines) {
        if ($line !~ m/^ /) {
            if ($line =~ m/:/) {
                @tokens = split ':', $line;
                $name = $tokens[0];
            }
            next;
        }

        if ($name && $line =~ m/ inet /) {
            @tokens = split /\s+/, $line;
            $addr = $tokens[2];
            if ($addr) {
                if ($name =~ m/^lo/) {
                    next;
                }
                print "$name $addr\n";
            }
            next;
        }
    }

    sleep 10;
}
